# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'galarm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for galarm
  pod 'Firebase/Analytics'

  target 'galarmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'galarmUITests' do
    # Pods for testing
  end

end
